### ISSUE TITLE
Set up hackathon web server for Docker applications

### ISSUE THREAD

**Issue by cmutel** [BONSAMURAIS/hackathon-2019#7]
- [x] Choose a web host and launch a server with a static IP
- [x] Email [Kasper Christiansen](mailto:kasperchristiansen@gmail.com) and redirect `*.bonsai.uno`
- [x] Set up NGINX for Dockerized web apps
- [ ] Write simple guide on common expectations for web apps (esp. data directories)
- [x] Set up [dribdat](https://datalets.ch/dribdat/) as `hackathon.bonsai.uno`
- [ ] Enter working group details into dribdat

**Comment by tngTUDOR** [comment]
We'll use digitalocean droplet with fedora 28

**Comment by tngTUDOR** [comment]
@cmutel : for dribdata is ithe fork or the origina that we must use?
https://datalets.ch/dribdat/
Oleg's fork: https://github.com/loleg/dribdat
original repo: https://github.com/dataletsch/dribdat
:question:

**Comment by cmutel** [comment]
They are both the same person (datalets is his consultancy). You can also ask @loleg directly if you have any problem getting it set up.

**Comment by tngTUDOR** [comment]
niiiiiice

**Comment by tngTUDOR** [comment]
the server is up and running at hackaton.bonsai.uno

When we have more apps, we should be able to run the containers in there

**Comment by loleg** [comment]
COOL!! @tngTUDOR two observations: you've missed the second "h" in hackathon, and you really should enable SSL. Let me know if there's anything I could help with.

**Comment by tngTUDOR** [comment]
argHHHHH the second *h*

**Comment by tngTUDOR** [comment]
> COOL!! @tngTUDOR two observations: you've missed the second "h" in hackathon, and you really should enable SSL. Let me know if there's anything I could help with.

yes, I could use some help on the ssl side. I started with let's encrypt but something is wrong (I think it is at at the DNS level)

**Comment by tngTUDOR** [comment]
> COOL!! @tngTUDOR two observations: you've missed the second "h" in hackathon, and you really should enable SSL. Let me know if there's anything I could help with.

It's done now. I had a little misconfiguration on my side, but it's all working (ssl included) now.
Thank you anyway.

**Comment by cmutel** [comment]
Closing as no longer relevant

**Comment by loleg** [comment]
@tngTUDOR @cmutel Thanks again for using Dribdat for your project. I'm at the moment organizing support, setting up an [OpenCollective](https://opencollective.com/dribdat) and planning dev sprints - would be great to get any feedback you have on our roadmap. 

- hackathon.bonsai.uno seems down. Is there a backup somewhere?
- Do you plan to keep using Dribdat again in the future?
- Did you need to make any changes, e.g. to run it as a droplet? 
- Any wishes at all from your side? 

Most of all I'd like to know if there's anything that could boost data gathering/purification efforts - if the hackathon platform could help lower the barrier to entry, give credit where it is due, drive engagement. E.g. see https://github.com/hackathons-ftw/dribdat/issues/98
