### ISSUE TITLE
Server can't connect to HTTPS correctly

### ISSUE THREAD

**Issue by cmutel** [BONSAMURAIS/hackathon-2019#9]
No certificate set up?

Let's encrypt is pretty trivial on NGINX, I can copy a config if needed.

@tngTUDOR I assume you have done this already on other servers.

**Comment by tngTUDOR** [comment]
I'ts on it's way ;)

**Comment by tngTUDOR** [comment]
Seems OK to me now (with the right spelling: https://hackathon.bonsai.uno )
https://www.ssllabs.com/ssltest/analyze.html?d=hackathon.bonsai.uno
